apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/upendrasahu/sam1-9643:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/upendrasahu/sam1-9643:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: sam1-9643
        chartPath: charts/sam1-9643
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/upendrasahu/sam1-9643"
          image.tag: "{{.DIGEST_HEX}}"
